<a href="https://colab.research.google.com/github/robertosgpontes/tec_prog_1/blob/main/ExerciciosNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lista de Exercícios de Numpy

Deverá ser entrege até **11/02/2023** por meio do github que foi informado por vocês no [formulário](https://forms.office.com/r/YV12vEXGYF) respondido na aula de 01/02.

A entrega pela github é parte da avaliação.

## Questão 1

Crie um array 100 com valores aleatórios e ache os valores máximo e mínimo

In [2]:
import numpy as np

In [8]:
arr = np.random.randint(0,100,100)
arr

array([46, 50, 66, 90, 20, 63, 36, 50, 49, 65, 50, 45, 69,  6, 60, 79,  5,
       19, 32, 21, 41,  2,  5, 11, 84, 57, 62, 50, 92, 76, 75, 35,  4, 67,
       46,  7, 76, 56, 37, 91,  1, 79, 35, 44, 68, 88, 80, 97, 39,  2, 67,
       92, 38, 46, 99, 54, 21, 23, 85, 68, 10, 27,  8, 98, 23, 55, 68,  7,
       40, 70, 13, 49, 42, 19, 58, 17, 80, 41, 65, 84, 60, 36, 96, 57, 72,
       79, 83, 71, 73, 17, 50, 67, 12, 90, 21, 94, 15, 27, 60, 42])

In [9]:
arr.min()

1

In [10]:
arr.max()

99

## Questão 2
Em Geometria Analítica, um **vetor** é uma quantidade que pode ser definida por um énuplo (uma sequência ordenada de *n* elementos) em que cada elemento representa a intensidade do vetor na direção especificada pela i-ésima componente desta sequência. 

Quando pensamos em duas dimensões, por exemplo, o vetor $R = (b,a)$ define, geometricamente, a entidade representada na figura abaixo, com componentes nos eixos x e y usuais.

<img src = "https://static.todamateria.com.br/upload/im/ag/image-721.jpg?auto_optimize=low" />

O **módulo** deste vetor, também chamado de intensidade, está geometricamente relacionado ao seu comprimento, e pode ser calculado diretamente pelas suas componentes, por meio de uma operação conhecida como **produto escalar** do vetor com ele mesmo. O módulo quadrático é expresso, desta forma, por:

$|A|^2 = \vec{A} \cdot \vec{A}$

Por outro lado, o produto escalar entre dois vetores $A = (a_{x}, a_{y})$ e $B = (b_{x}, b_{y})$ é dado por:

$\vec{A} \cdot \vec{B} = a_{x} \times b_{x} + a_{y} \times b_{y}$ (e esta definição vale para qualquer que seja a dimensão do vetor).

O módulo quadrático de um vetor é, portanto:

$|A|² = a_{x}^2 + b_{x}^2$.

Dado o exposto acima, escreva uma função que retorne o módulo de um vetor n-dimensional qualquer.

In [12]:
a = np.array([1,2])
b = np.array([3,4])

In [16]:
def modulo_quadratico(vetor):
  soma_quad = 0
  for elemento in range(vetor.shape[0]): #como se fosse um len()
    soma_quad += vetor[elemento]**2
  modulo = np.sqrt(soma_quad)
  return modulo

In [17]:
modulo_quadratico(a)

2.23606797749979

In [21]:
modulo_quadratico(b)

5.0

## Questão 3

Em uma **análise de regressão**, usualmente estamos interessados em descrever relações entre variáveis de um dado conjunto de dados por meio de uma **função** que descreva, o tanto quanto possível, estas relações.

Por exemplo, no gráfico abaixo, os pontos vermelhos relacionam as medidas das duas variáveis sendo avaliadas (nos eixos x e y); e a linha azul aproxima a relação entre elas por uma função linear.

![Normdist_regression.png](https://miro.medium.com/v2/resize:fit:786/format:webp/1*LEmBCYAttxS6uI6rEyPLMQ.png)

É possível ver que nem todos os pontos obedecem exatamente à relação ditada pela reta (isto é, há pontos que não estão exatamente "sobre a reta"; mas, sim, ligeraimente acima, ou abaixo, dela). Isto, contudo, é esperado em um modelo de regressão, por inúmeras fontes de incerteza associadas às medições.

Uma das métricas que utilizamos para avaliar a qualidade de uma regressão é o **erro quadrático médio (EQM)**, que mensura a diferença total entre cada predição da regressão ($y_{prediction}$; que no nosso caso seriam os valores de y para a reta azul) com o valor real de cada i-ésima medida ($y_{i}$; que no nosso caso seriam as coordenadas y para cada ponto vermelho do gráfico). O EQM pode ser definido como:

$EQM = \frac{1}{n}\sum_{i=1}^{n}(y_{prediction} - y_{i})^2$.

Isto posto, escreva uma função que calcule o EQM recebendo, como entrada, os vetores $y_{prediction}$ e $y_{i}$. Por exemplo, digamos que sua função se chame *calculate_eqm*, ela deve operar da seguinte forma:

In [ ]:
# dados dois arrays quaisquer de mesmo tamanho, a função deve retornar o EQM
y_prediction = np.array([1,2,3])
y_i = np.array([0,0,3])
calculate_eqm(y_prediction,y_i)

1.6666666666666665

In [28]:
# Solução
def calculate_eqm(yp, yi):
  quad_diff = 0
  fator = 1/(yp.size)
  for elemento in range(yp.shape[0]):
    quad_diff += (yp[elemento] - y_i[elemento])**2
  return fator*quad_diff

In [29]:
y_prediction = np.array([1,2,3])
y_i = np.array([0,0,3])
calculate_eqm(y_prediction,y_i)

1.6666666666666665

## Questão 4

Crie um array 2D (bidimensional) com 1 na borda e 0 dentro

In [31]:
arr2d = np.array([[1,1,1], [1,0,1], [1,1,1]])
arr2d

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

## Questão 5

Como adicionar uma borda de 0's ao redor de um array 2D (bidimensional) existente

In [32]:
borda_arr = np.pad(arr2d, pad_width=1, mode='constant', constant_values = 0)
borda_arr

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])

## Questão 6

 A eletroencefalografia (EEG) é uma técnica que mensura potenciais elétricos cerebrais em diversas regiões do escalpo do paciente. Suponha que você recebeu um conjunto de dados na forma de uma matriz de 64 x 512 elementos, em que cada linha contém o sinal gravado em um dos **eletrodos** espalhados pelo escalpo em um exame de EEG, e cada coluna contém um valor de potencial elétrico, em microvolts. 

Como o sinal de EEG é muito suscetível a ruídos externos (interferências na qualidade do sinal), uma operação comum para atenuar a interferência no sinal consiste em tirar a média do potencial elétrico de todos os eletrodos, e subtrair este valor de cada um deles. Isto atenua fontes de ruído ao sinal comuns a todos os eletrodos. Em termos matemáticos, o sinal processado por esta operação, $X_{e,i}$ para cada eletrodo (e) e amostra (i), é dado por:

$X_{e,i} = \hat{X_{e,i}} - \frac{1}{N}\sum_{e=1}^{N}\hat{X_{e,i}}$,

em que $\hat{X_{e,i}}$ representa o sinal original (ou seja, é a matriz de entrada de 64 x 512 elementos), e $N$ indica o total de eletrodos.

Com o exposto acima, escreva uma função que retorne uma matriz com os sinais de EEG processados conforme a operação mencionada. Sua função deve operar conforme o exemplo abaixo.

In [34]:
# vamos supor uma matriz de entrada gerada por dados aleatórios
X = np.random.randn(64,512)
X.shape # apenas para verificar as dimensões

(64, 512)

In [ ]:
# a função deve executar a operação equacionada anteriormente, retornando uma nova matriz
X_processado = process_EEG_signal(X)
X_processado.shape

(64, 512)

In [ ]:
# Somando as diferenças entre cada elemento das duas matrizes, apenas para ilustrar que elas não são iguais
(X_processado - X).sum()

-53.08727366483029

In [ ]:
# Visualizando as matrizes, para verificar uma vez mais que, de fato, os elementos são diferentes
X

array([[ 0.29305925,  0.89663038, -0.61032202, ..., -0.88086364,
        -0.8818789 ,  0.51260497],
       [-0.01274415,  1.05439522,  0.47958092, ..., -2.15387924,
         0.70721168,  0.97029889],
       [ 1.09478371, -0.16120847,  1.58400361, ...,  0.20981813,
         2.17373837,  0.94032162],
       ...,
       [-0.45294842, -2.28939505,  1.10111998, ...,  1.63581703,
        -0.39394924, -1.13400723],
       [-0.22669886,  0.25413429, -1.17870637, ..., -0.09509442,
         0.90733806,  0.37999411],
       [ 0.15476933, -0.03654717, -1.09982762, ...,  0.67600047,
        -0.84533328, -0.56433144]])

In [ ]:
# Matriz após o processamento descrito no enunciado
X_processado

array([[ 0.36713022,  0.85772513, -0.54902169, ..., -0.85626087,
        -0.97611435,  0.51718998],
       [ 0.06132682,  1.01548997,  0.54088126, ..., -2.12927647,
         0.61297623,  0.97488389],
       [ 1.16885469, -0.20011372,  1.64530394, ...,  0.23442091,
         2.07950292,  0.94490663],
       ...,
       [-0.37887744, -2.3283003 ,  1.16242031, ...,  1.6604198 ,
        -0.4881847 , -1.12942223],
       [-0.15262788,  0.21522904, -1.11740604, ..., -0.07049164,
         0.81310261,  0.38457911],
       [ 0.22884031, -0.07545242, -1.03852729, ...,  0.70060324,
        -0.93956874, -0.55974643]])

In [37]:
# Solução
def matriz_retorno(matriz):
  media = (matriz.sum())/(matriz.size)
  m_processada = matriz - media
  return m_processada

In [36]:
X

array([[ 0.81952307, -0.53026126,  0.09718467, ...,  1.94948105,
         1.08934236,  0.83902832],
       [ 0.07168644,  0.3018321 ,  0.55005219, ..., -1.41098842,
         0.39523723,  1.55604174],
       [ 1.93285489,  0.30334507,  1.76387938, ..., -0.21404572,
         1.00628624, -1.02514807],
       ...,
       [ 0.25344119,  1.72266636, -0.08847878, ..., -0.44906022,
        -0.38210135, -1.38889444],
       [-2.30363956, -0.81915214, -0.2162751 , ...,  0.7673799 ,
         0.62159052,  2.72762584],
       [ 0.52377831, -0.43505639, -0.61879018, ...,  0.49011509,
         1.25822708,  0.20188562]])

In [41]:
X_EEG = matriz_retorno(X)
X_EEG

array([[ 0.81685199, -0.53293235,  0.09451359, ...,  1.94680997,
         1.08667128,  0.83635724],
       [ 0.06901536,  0.29916102,  0.54738111, ..., -1.4136595 ,
         0.39256615,  1.55337066],
       [ 1.93018381,  0.30067398,  1.7612083 , ..., -0.2167168 ,
         1.00361516, -1.02781915],
       ...,
       [ 0.2507701 ,  1.71999528, -0.09114986, ..., -0.4517313 ,
        -0.38477243, -1.39156552],
       [-2.30631064, -0.82182322, -0.21894618, ...,  0.76470882,
         0.61891944,  2.72495476],
       [ 0.52110723, -0.43772747, -0.62146126, ...,  0.48744401,
         1.255556  ,  0.19921454]])

In [43]:
X_EEG.shape

(64, 512)

In [42]:
(X_EEG - X).sum()

-87.5259849114715

## Questão 7

Em estatística, um **outlier** é um valor que destoa consideravelmente da distribuição à qual está associado. Um dos critérios para idenficar outliers consiste em encontrar a **distância interquantil** (IQR), ou seja, a diferença entre o terceiro (Q3) e o primeiro quartis (Q1) da distribuição, e tomar como outliers todos os pontos abaixo de 1.5*IQR - Q1, ou acima de 1.5*IQR + Q3.

<img src = "https://blog.curso-r.com/images/posts/banner/outlier.webp" />

Escreva uma função que, dada uma matriz de dados de entrada de dimensões $N_{observações} \times N_{features}$ retorne três requisitos: 
- uma matriz booleana indicando a existência de outliers nos dados de entrada;
- a quantidade de outliers
- quem são os outliers (os valores).

**Algumas definições:**
- um *quantil* divide a distribuição, após ordenados os pontos, segundo algum ponto de corte;
- o **primeiro quartil** é o ponto para o qual 25 % dos valores da distribuição estão abaixo dele;
- o **terceiro quartil** é o ponto para o qual 75 % dos valores da distribuição estão abaixo dele.

Pode ser útil consultar a função **numpy.quantile**.

Exemplo de operação da função:

In [ ]:
# Geremos um conjunto de dados qualquer
X = np.random.randn(300,15)
X

array([[-2.02108952,  0.57945921, -2.23074965, ..., -0.60349514,
         0.92180452, -0.15625722],
       [ 0.24904397,  0.03493447,  0.3515052 , ..., -0.46950081,
         0.20361331,  0.02715956],
       [ 0.55902525, -0.48435434,  0.90413414, ..., -0.54425743,
        -0.80769134, -0.07912549],
       ...,
       [-1.04069388, -0.24245725, -2.00308877, ...,  0.4084777 ,
        -1.81516131,  0.39063118],
       [-1.39275097,  0.3989636 ,  0.2926223 , ...,  1.2620666 ,
         0.72262949,  1.50737559],
       [ 0.15922011, -0.79810788, -1.60939896, ..., -0.08214499,
        -0.13167475,  0.15990558]])

In [ ]:
# identificamos os requisitos com nossa com nossa função "locate_outliers"
is_outlier, outliers_count, outliers = locate_outliers(X)

In [ ]:
is_outlier

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [ ]:
outliers_count

44

In [ ]:
outliers

array([-2.67240384,  3.00270904,  3.62317101,  3.18867865,  2.55581522,
       -2.82091429,  2.8757892 ,  2.70666036,  3.19514999, -3.40550318,
       -3.39825827,  2.6727295 ,  2.54498296, -2.69447104,  3.19521603,
        2.66372172, -2.77444948,  2.77421152,  2.69992869, -2.84831109,
       -2.83695779, -2.45908227,  3.07802106,  2.89314015, -2.68574682,
       -2.85019494,  2.43399574,  2.44291266, -2.92595937, -2.95911074,
       -3.03966003,  2.77543068, -2.67368414, -2.79965402, -3.0501958 ,
       -2.5437387 ,  3.08550649, -3.17666255, -3.05795476, -3.09826467,
        3.1399469 ,  3.18141942,  2.90564257, -2.89505054])

In [53]:
def locate_outliers(matriz):
    outliers_bool = np.zeros(matriz.shape, dtype=bool)
    contagem_outliers = 0
    outliers = []
    for coluna in range(matriz.shape[1]):
        q1, q3 = np.quantile(matriz[:,coluna], [0.25, 0.75])
        iqr = q3 - q1
        outliers_coluna = ((matriz[:,coluna] < (q1 - 1.5 * iqr)) | 
                           (matriz[:,coluna] > (q3 + 1.5 * iqr)))
        outliers_bool[:,coluna] = outliers_coluna
        contagem_outliers += np.sum(outliers_coluna)
        outliers = np.append(outliers, matriz[outliers_coluna,coluna])
    return outliers_bool, contagem_outliers, outliers

In [17]:
X = np.random.randn(300,15)
X

array([[-0.25174057,  1.13160081,  0.82708587, ..., -2.8140422 ,
         0.52645024, -0.15388782],
       [-0.22827465, -2.0445559 ,  0.07817017, ..., -0.73542148,
        -1.17613934, -0.11768232],
       [-0.75764831, -0.22046453, -0.10155415, ...,  0.37248469,
         0.36272878, -1.5813477 ],
       ...,
       [-0.34016766,  0.89557253, -0.02264033, ..., -1.31596104,
         1.35131063,  0.77463193],
       [-1.11678651,  0.02924802, -0.31490852, ..., -1.07969162,
         1.00676839, -0.61800303],
       [-0.65298956, -1.83019593,  2.66650353, ...,  0.4888508 ,
        -0.10177114, -1.98501122]])

In [58]:
is_outlier, outliers_count, outliers = locate_outliers(X)
print(f'É outlier?\n {is_outlier},\n Quantos são? {outliers_count},\n Quem são?\n {outliers}')

É outlier?
 [[False False False ...  True False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]],
 Quantos são? 32,
 Quem são?
 [ 2.76253522  3.20796019  3.11567718 -2.95943881 -3.05162395 -3.1396546
  3.28994538 -2.90991275 -2.52819964 -2.53015861 -3.37486874 -3.54555785
  2.64237228 -2.99805137 -3.71741777  2.72119451  2.70674919  3.01015485
  2.80889816  2.78386402 -2.88015713 -2.9108389  -3.69356821 -2.6448668
 -2.70805206  2.72942915 -2.92473752 -3.50302292 -2.8140422  -2.78888878
 -2.91897196  3.02232439]


## Questão 8

Crie um vetor com valores que vão de 1 até 21 de dois em dois, a partir da função arange

In [59]:
vetor = np.arange(1,22,2)
vetor

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

## Questão 9

Crie um array de 10 com valores aleatórios

In [63]:
arr = np.random.rand(10)
arr

array([0.94194626, 0.40440916, 0.27655488, 0.299777  , 0.12437117,
       0.39860079, 0.70551024, 0.1414923 , 0.28023737, 0.05934168])

In [68]:
arr.std()

0.2592317452268859

## Questão 10

Em estatística, a normalização de uma distribuição de dados pode ser feita subtraindo o valor médio da distribuição de cada valor do conjunto de dados, dividindo o resultado pelo desvio-padrão da distribuição. Escreva uma função que normalize os dados recebidos por um array numpy qualquer, conforme descrito anteriormente.

In [65]:
def normalizacao(array):
  valor_medio = array.mean()
  desvio_padrao = array.std()
  arr_norm = []
  for elemento in range(array.shape[0]):
    novo_valor = (array[elemento] - valor_medio) / desvio_padrao
    arr_norm = np.append(arr_norm, novo_valor)
  return arr_norm


In [66]:
normalizacao(arr)

array([ 2.23245102,  0.15887358, -0.33433099, -0.24475045, -0.92138761,
        0.13646749,  1.32038672, -0.85534194, -0.32012558, -1.17224223])

## Questão 11

Escreva uma função em numpy que receba um array contendo notas de uma turma de 100 estudantes. Considere que a nota de aprovação da turma é 5.0. A função deve retornar, em um array numpy, nesta ordem:
- a média e o desvio-padrão das notas da turma;
- o número de notas maiores que 7.0;
- o número de reprovações da turma;
- a menor nota da turma;
- a maior nota da turma.

In [7]:
def situacao(notas):
  media = notas.mean()
  desvio = notas.std()
  menor = notas.min()
  maior = notas.max()
  notas_maiores = 0
  reprovados = 0
  for nota in notas:
    if nota > 7:
      notas_maiores += 1
    elif nota < 5:
      reprovados += 1
  return np.array([media,desvio,notas_maiores,reprovados,menor,maior])


In [11]:
notas = np.random.rand(100)*10
notas = np.around(notas, decimals=1)
notas

array([ 1.5,  8.7,  2.2,  0.5,  9.1,  3.9,  4.2,  1.1,  6.5,  5.8,  9.9,
        8.3,  5.9, 10. ,  4.6,  7. ,  9.7,  5.7,  1.7,  1.2,  3.7,  8.7,
        9. ,  6.1,  5. ,  9.5,  3.7,  2.3,  3.3,  7.4,  6.9,  3.4,  1.1,
        2.3,  8.1,  2.5,  0. ,  4.2,  8.6,  7.4,  3.5,  1.4,  2.5,  1.6,
        7.1,  1.2,  5.1,  2.8,  8.4,  5.8,  4.7,  7.4,  9.3,  7.8,  0.9,
        6.9,  0.8,  9.6,  7.3,  1.5,  1.1,  0.9,  1.8,  7.7,  9.3,  7.1,
        1.8,  3.2,  1.6,  2.6,  0.4,  4.1,  8.6,  7.5,  4.2,  7.5,  2.8,
        6.1,  2.6,  0.9,  5.4,  3.1,  8.1,  2.6,  4.4,  4.5,  7.7,  5.6,
        6.4,  7.7,  9.6,  8.9,  7.7,  9.3,  3.4,  2.3,  4.9,  0.4,  1.2,
        0.5])

In [12]:
situacao(notas)

array([ 4.918     ,  2.97416812, 33.        , 52.        ,  0.        ,
       10.        ])